### ISSUE TITLE
library

### ISSUE THREAD

**Issue by ho33ein19** [naman14/Timber#1]
hi please send libraries to ho33ein.b@gmail.com thank you

**Comment by naman14** [comment]
Can you be more specific about your question?

**Comment by TheLester** [comment]
Jake Wharton has logging library with same name

**Comment by ho33ein19** [comment]
Please use libraries and their libs folder upload

**Comment by Kernald** [comment]
They are fetched by Gradle, you have the list there: https://github.com/naman14/Timber/blob/master/app/build.gradle#L29
