### ISSUE TITLE
Android Wear Support 

### ISSUE THREAD

**Issue by N07070** [naman14/Timber#105]
Hello, 

I own a Moto 360, and I would find it very awesome to be able to have a next / previous control on the watch. 

For example, the Soundcloud app does this. 

Could this feature be added? Thanks!

**Comment by naman14** [comment]
Started working on this

**Comment by naman14** [comment]
Play/Pause, Next, previous and volume controls added ifor wear in 386f51e0a09397d191652043629215f9f18c39eb

**Comment by naman14** [comment]
Also working on creating a separate UI for wear for browsing all songs and playing from watch itself

**Comment by N07070** [comment]
Wow, awesome ! I'll have a close look at the code, thanks for working on this !
