### ISSUE TITLE
[Minor Issue] "Now playing" theme changing

### ISSUE THREAD

**Issue by collectorgeneral** [naman14/Timber#107]
There is a minor issue with changing the "Now Playing" theme changer. If you are on the now playing screen and change the theme, the change does not reflect immediately. You have to re open the now playing app for it to take place. Not restarting the app in typical sense, but for instance, pressing back to browse the albums and again going back to the now playing screen. Only then it gets updated. I am almost certain that it was not the behaviour before the update. Nothing major, but worth noting.

**Comment by naman14** [comment]
This was the behaviour all along as no code is there to recreate the screen on theme change, fixing that

**Comment by naman14** [comment]
Fixed in da0e74e5cbe3a92853cbee0623b21a5f3803bed5
