### ISSUE TITLE
[Bug] Now playing playlist empty when accessing app from notification

### ISSUE THREAD

**Issue by collectorgeneral** [naman14/Timber#108]
When you select the first two "Now Playing" themes, you get to see the songs in the album you are playing. Now when I click the notification to access the app, the playlist shows up as blank. However, when you launch the app normally, it shows up just fine. 
![screenshot_2015-12-23-12-00-01](https://cloud.githubusercontent.com/assets/15972594/11979853/001fd012-a96d-11e5-8cf8-c8e5124d213e.png)
![screenshot_2015-12-23-12-00-10](https://cloud.githubusercontent.com/assets/15972594/11979854/00238d74-a96d-11e5-97d9-8c83982f2e47.png)

**Comment by naman14** [comment]
Fixed

**Comment by collectorgeneral** [comment]
Thanks! Can confirm it is fixed!
