### ISSUE TITLE
[Enhancement Request] Access music when launching app from notification

### ISSUE THREAD

**Issue by collectorgeneral** [naman14/Timber#109]
A couple of people pointed this out, and I would like to point this to the dev as well. Please include the option to browse music when launching the app from the notification bar. The current behaviour is that it just shows the player, and when you press the back key, it just exits. It would be nice if we could browse music by accessing the app from the notification bar. It is inconvenient to keep searching for the app icon and launch it whenever we want to change the music. It is much more easier to access the app from the notifications.

**Comment by naman14** [comment]
Fixed, will be available in next release

**Comment by collectorgeneral** [comment]
Thanks! It works!
