### ISSUE TITLE
No reaction to Bluetooth button presses 

### ISSUE THREAD

**Issue by yuukiw** [naman14/Timber#15]
My headset is an Sony sbh50.
Device Samsung Galaxy s6 Edge. 
Android 5.1.1

**Comment by naman14** [comment]
Can you verify if it's working in latest release?

**Comment by yuukiw** [comment]
this video should answer it ;)
https://drive.google.com/file/d/0B94u0_R6vixWTEZxOEtCTDI3U1E/view?usp=sharing

**Comment by yuukiw** [comment]
after the lastes uppdate it wont work again

**Comment by naman14** [comment]
Hmm, I haven't done any code changes related to this which can cause it to not work again.
I will look again though

**Comment by madeindjs** [comment]
It also won't works for me with my Pionner in my Car:

* HTC One M8 - Android 6.0
* Pionner DEH-X5600BT
* Timber 0.14b

**Comment by regagain** [comment]
Same issue for me:
* Nexus 6P / Nougat 7.1.2.
* Timber 0.2b from F-Droid.

**Comment by AntiGuide** [comment]
Same issue for me but with a cable headset:

- Samsung Galaxy S8+ / Nougat 7.0
- Timber 0.4b

**Comment by justphillip** [comment]
Same issue here:

- Samsung Galaxy A5 (2016) / Android 6.0.1
- Timber 0.5b
- Default Samsung Cable Headphones

**Comment by rivaldi8** [comment]
It would be nice if someone else could confirm the fix. It works for me with:
- bq Aquaris U Plus
- Android 7.1.1
- Heaphones Sony MDR-EX110AP

**Comment by deelite** [comment]
Here it doesn't work.

- Motorola Moto G5
- ViperOS 3.0-20170812 (Android 7.1.2)
- Headphones Philips SHB5950

**Comment by AntiGuide** [comment]
Doesn't work here:

- Samsung Galaxy S8+
- Android 7.0
- Headphones Harman AKG

**Comment by anburocky3** [comment]
Doesn't work here too:
Lenovo K3 Note
Android 6.1
Headphone Samsung, Philips

**Comment by rivaldi8** [comment]
To make testing of the fix easier I've prepared an APK [here](https://my.owndrive.com/index.php/s/mzloqZ1d8ZGZT1r). It will be installed as an independent application with the name "Timber devel", so it won't interfere with the official Timber you already have installed. It still doesn't solve the problem for all cases, though:

- Pressing the button after the application has been killed does nothing. It should restart the application service and start playing.
- If the application is started after having been killed, pressing the button still doesn't make it start playing. It only starts working after having started playing a song manually from the UI.

I still haven't find out why these don't work.

This APK also contains the changes in [these pull requests](https://github.com/naman14/Timber/pulls/rivaldi8). If you feel like testing them too, any feedback would be greatly appreciated. Thanks!

**Comment by anburocky3** [comment]
Does anyone fixed it? Developer busy?
