### ISSUE TITLE
Error To Import

### ISSUE THREAD

**Issue by joseliko7** [naman14/Timber#150]
Error:Execution failed for task ':app:compileDebugAidl'.

> java.lang.RuntimeException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\josel\AppData\Local\Android\sdk\build-tools\23.0.0\aidl.exe'' finished with non-zero exit value 1

???????

**Comment by MrShuHong** [comment]
try clean project
