### ISSUE TITLE
[Feature request] Home screen widget

### ISSUE THREAD

**Issue by madsherlock** [naman14/Timber#154]
Is it possible to add a home screen widget? I liked the one from the HTC player with album art, prev, play / pause, and next (4x1). It's a nice alternative to the notification bar.

**Comment by alexisju** [comment]
:+1:

**Comment by nazar-pc** [comment]
Preferably transparent (or configurable) widget.
I'm going to replace mighty proprietary PowerAmp with this player, currently my widget looks like this:
![screenshot_20161012-074001](https://cloud.githubusercontent.com/assets/928965/19297621/6f03d5cc-904f-11e6-865d-21b1ed05623c.jpg)

**Comment by nv95** [comment]
Already added

**Comment by nazar-pc** [comment]
I've seen it already, it looks nice in 4x1 size, but doesn't scale well for 4x2 (don't think more makes sense).
Could you center on bigger sizes like on screenshot above?

**Comment by nazar-pc** [comment]
Complete transparency would be a nice option too if not too difficult to implement.

**Comment by nv95** [comment]
Ok, I'll do it
