### ISSUE TITLE
error

### ISSUE THREAD

**Issue by armoun** [naman14/Timber#167]
`android:src="@drawable/abc_ic_menu_moreoverflow_mtrl_alpha` not found in drawable path

**Comment by cellpacing** [comment]
me too ，I Replace the other pictures  but run In the following error :
java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.TintManager"

**Comment by naman14** [comment]
I have an exam in some time, will check this after that. Probably something to do with support library. Maybe they removed this drawable in latest appcompat

**Comment by lisenhei** [comment]
If you have this problem, you can change the android.support.v7 dependencies version to a newer version, such as 23.2.1

**Comment by RahulSDeshpande** [comment]
Hi @lisenhei,

Even if I change the android.support.v7 dependencies version to a newer version, such as 23.2.1,
I am getting the below error for ``android:src="@drawable/ic_menu_moreoverflow_mtrl_alpha"``

**``No resource found that matches the given name (at 'src' with value '@drawable/ic_menu_moreoverflow_mtrl_alpha')``**

Please help !!

Cheers :+1:

**Comment by xiayouli0122** [comment]
Hi @RahulSDeshpande  I change the android.support.v7 dependencies version to  23.3.0, and the issue is solved.

**Comment by my-sunshine** [comment]
I change the android.support.v7 dependencies version to 23.3.0, and the issue is solved too

**Comment by armoun** [comment]
android:src="@drawable/abc_ic_menu_moreoverflow_mtrl_alpha not found in drawable path

`

> error work by **android.support.v7** dependencies version to **23.3.0** or newer
`
