### ISSUE TITLE
Error:(58, 13) Failed to resolve: com.github.naman14:app-theme-engine:-SNAPSHOT

### ISSUE THREAD

**Issue by 4sskick** [naman14/Timber#169]
After I loaded the project I got this error, only this one [Error:(58, 13) Failed to resolve: com.github.naman14:app-theme-engine:-SNAPSHOT]. 
Can you explain to me what's wrong?

**Comment by viacheslavokolitiy** [comment]
Did you update gradle plugin version locally ? I've updated and received this error #168

**Comment by viacheslavokolitiy** [comment]
#168

**Comment by viacheslavokolitiy** [comment]
Try use `0.5.1` instead of `-SNAPSHOT`

**Comment by 4sskick** [comment]
Solved, Thank you

**Comment by naman14** [comment]
I have fixed build errors in previous commit
