### ISSUE TITLE
Is the app not in development anymore? Like why are we not seeing updates yet? thankyou

### ISSUE THREAD

**Issue by karanschhabra** [naman14/Timber#173]

**Comment by wdpm** [comment]
You can see [this link](https://github.com/naman14/Timber/issues/163).
The author say that he is a 2nd year Engineering student with lots of other things to work on including studies and other side projects.He can only contribute small amount of time on Timber.
@karanschhabra

**Comment by karanschhabra** [comment]
Oh yeah I know the feel but really we just want it to be stable and get out of beta you know once and for all
all the best naman! cheers(Y) and thanks!
