### ISSUE TITLE
getting issue Error:(58, 13) Failed to resolve: com.github.naman14:app-theme-engine:0.5.1 on Android Studio 2.0

### ISSUE THREAD

**Issue by PratapVhatkar** [naman14/Timber#177]
I have already tried using local & default gradle settings

**Comment by mayank26saxena** [comment]
I'm facing the same issue.

**Comment by mayank26saxena** [comment]
@PratapVhatkar were you getting the following errors too ?
1) Error:(55, 13) Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.3
2) Error:(61, 13) Failed to resolve: com.github.afollestad.material-dialogs:commons:0.8.5.3

**Comment by naman14** [comment]
I can't do anything here. Please report the issue to Jitpack. afollestad is in the process of moving his libraries to jcenter due to unreliable build from Jitpack

**Comment by mayank26saxena** [comment]
He just moved his libraries to jcenter and they're getting compiled now! 
Still facing issue while compiling -
compile('com.github.naman14:app-theme-engine:0.5.1@aar') {
        transitive = true
}

**Comment by naman14** [comment]
Cool, I will also update my fork of app-theme-engine to include these new jcenter builds (app-theme-engine internally uses material-dialogs) then it should work

**Comment by mayank26saxena** [comment]
Yeah, hopefully there won't be any build errors after that

**Comment by naman14** [comment]
Published a new release on https://github.com/naman14/app-theme-engine and here. Build errors should be fixed now
