### ISSUE TITLE
Urgent:Error on now playing activity

### ISSUE THREAD

**Issue by fantasticrahulrai** [naman14/Timber#184]
@Override
    public int getToolbarColor() {
        return Color.TRANSPARENT;
    }

says method doesn't override method from superclass

**Comment by HumbleBeeBumbleBee** [comment]
Just comment out @Override

**Comment by naman14** [comment]
That will solve the error but don't do that, will not solve what this method is actually there for. 
There have been some changes in the app-theme-engine library. I will clear out all issues this weekend

**Comment by aniketjdhv1** [comment]
Commenting out @Override still gives the same error. Not able to make it transparent.

**Comment by s3condAtall** [comment]
WORKAROUND: Import [this project](https://github.com/naman14/app-theme-engine) as library to timber project, edit build.gradle and it will fix the error.

**Comment by ridhwanyt** [comment]
hey! how to import it? can you please help me! what and where to edit in build.gradle.... im new to android developing please help!!

**Comment by ridhwanyt** [comment]
@HumbleBeeBumbleBee Can you send me the project after fixing it? PLEASEE?

**Comment by anburocky3** [comment]
The above problem has been fixed in the latest build ;)
