### ISSUE TITLE
Publishing on F-Droid

### ISSUE THREAD

**Issue by Calinou** [naman14/Timber#19]
What should be done in order to publish this on [F-Droid](https://f-droid.org/)?

Are there any proprietary dependencies? Is it possible to build without Google Play Services, in case it is used?

**Comment by Allsimon** [comment]
The only thing that "might" be problematic are the jcenter repositories but I can't find what needs it... And it builds fine without it, they probably aren't used anymore

I can create the request for F-Droid if @naman14 wills it

**Comment by naman14** [comment]
@Allsimon jcenter is used to build most of the libraries in gradle. 
You can surely try creating the request for F-Droid inclusion.

**Comment by Allsimon** [comment]
Doh! I mistook jcenter for sonatype. My merge request has been accepted, the app should be there in a few hours/days

**Comment by utack** [comment]
I think this can be closed and marked as fixed now?

**Comment by naman14** [comment]
Yeah sure, this can be closed now
