### ISSUE TITLE
Wrong song order in albums

### ISSUE THREAD

**Issue by spaceisstrange** [naman14/Timber#2]
I don't know why the order of the songs in the album are wrong, as you can see in the screenshots below, the order is totally random:

![Album 1](http://i.imgur.com/7xAALuO.png)
![Album 2](http://i.imgur.com/H3MetAk.png)

Is this a known issue? Thanks for the app, it's wonderful nonetheless :smile:

**Comment by naman14** [comment]
Yeah, its a known issue, will fix it in next release, forgot to add the sorting order for album songs😑

**Comment by spaceisstrange** [comment]
Totally normal stuff hahaha. Don't worry, you're doing a great job!

**Comment by naman14** [comment]
Hey, just checked the code and I am sorting the albums with default sort order. As you can see in the screenshot, the songs are sorted alphabetically. Maybe I will add options for more sort orders probably in some next releases

**Comment by spaceisstrange** [comment]
I think that the default order should be by song number and not alphabetically, but an option to choose between them would be great!

**Comment by naman14** [comment]
Added in 8a6717d02f4a39fae6665718d4a459f2ffbe43ff. Album songs can be sorted by A-Z,  Z-A, Year, Track Number and by Duration. Sort orders have also been added for songs, albums and artists
