### ISSUE TITLE
Provide pure floss build flavor

### ISSUE THREAD

**Issue by krt16s** [naman14/Timber#219]
Crashlytics has recently been added (https://github.com/naman14/Timber/pull/217). This is non-free software and we at f-droid cannot build further versions. Could you provide a pure gradle vuld flavor that does not use non-free software?

**Comment by naman14** [comment]
Hi, I have pushed a new branch (f-droid) that doesn't have crashlytics.
Let me know if its fine or if something else is required.

**Comment by krt16s** [comment]
If that's easier to maintain for you, I am fine with that. https://gitlab.com/fdroid/fdroiddata/commit/3be232f9bd7331309743934b304a496773ddd55f should build tonight. Thanks for the quick fix.

**Comment by naman14** [comment]
@krt16s There were some crashes on the previous version which I have fixed now. Can you please initiate the latest build process for f-droid. 
Thanks

**Comment by krt16s** [comment]
I don't see any new commits in the f-droid branch, 0.2b (14) is build from 3406f4e932a8c93b865ca6788a21d36be129fbca which is still the latest commit there.

**Comment by naman14** [comment]
Sorry, just checked the commit history on Gitlab and the update to 14(0.2b) is there, but the repository page on f-droid has v13 currently (https://f-droid.org/repository/browse/?fdfilter=Timber&fdid=naman14.timber)

**Comment by krt16s** [comment]
It's already build, see https://f-droid.org/wiki/page/naman14.timber, just waiting for publishing. Should be fixed in a couple of hours.

**Comment by naman14** [comment]
Okay, thanks
