### ISSUE TITLE
Folder View on Timber?

### ISSUE THREAD

**Issue by anburocky3** [naman14/Timber#221]
I heard you will release the Folder view options a year back? did you released the folder view version?
Looking forward to have Folder View Option in Timber. ?

**Comment by nv95** [comment]
I make folder view mode, but i don`t know, how to get track id by filename. Can anyone help me?

**Comment by naman14** [comment]
You can use 'MusicPlayer.openFile(String filePath)' 

You can also checkout the actual implementation in 'MusicService.openFile(String path)`

**Comment by naman14** [comment]
I will review and merge other pull requests as soon as I have a little bit of free time. 
Thanks for your contributions!

**Comment by nv95** [comment]
Ok, it works, but no track metadata displays(

**Comment by naman14** [comment]
`MusicPlayer.playOrPause();` should result in `onMetaChanged` being called.

You can create a pull request of existing implementation. I will implement the meta fetching if you are having trouble.

**Comment by nv95** [comment]
ok thanks

**Comment by naman14** [comment]
Added in the latest release
