### ISSUE TITLE
[Feature request] Add support for showing lyrics

### ISSUE THREAD

**Issue by hefuyicoder** [naman14/Timber#226]
Hi!
I think it will be more wonderful if timber support to show lyrics while playing music,do you think so?

**Comment by fedor1113** [comment]
I (personally) agree.) That'd be a wonderful feature to add.

**Comment by nv95** [comment]
Good idea, but what services can be used for it?

**Comment by fedor1113** [comment]
In some songs lyrics may be added in the file itself. Then it would be nice to be able to see them.

**Comment by fedor1113** [comment]
To better explain what I mean - here is the spec (if I got it correctly): http://id3.org/Lyrics3v2

**Comment by mihawk90** [comment]
The Lyrics3v2 tag is Deprecated as far as I know, only with the ID3v1 tag.

There is now the [USLT Field in ID3v2](http://id3.org/id3v2.3.0#Unsychronised_lyrics.2Ftext_transcription).

Though if I read this right this is already in the `LyricsExtractor.java`.


In addition to that, would it also be possible to implement timed lyrics ([SYLT field](http://id3.org/id3v2.3.0#Synchronised_lyrics.2Ftext)) and let them scroll? It's not really important, [QuickLyric](https://f-droid.org/repository/browse/?fdfilter=QuickLyric&fdid=com.geecko.QuickLyric) also does scrolling though, if you want to implement it and need some inspiration :)

**Comment by naman14** [comment]
Lyrics support have been added now, will publish a new release on Play Store soon

**Comment by fedor1113** [comment]
Great! I hope that F-droid version will also be available...
