### ISSUE TITLE
Does not fetch album art

### ISSUE THREAD

**Issue by GitHorst** [naman14/Timber#247]
in the library, in the "artists" view the app downloads and displays the artist's images correctly. in "album" view however, it does not display any album art except the embedded ones.

since i installed this from f-droid, i am stil on v0.2b.

please let me know, if you need more information on this!

thanks for your efforts with this really nice player!

**Comment by wiomoc** [comment]
Not a bug, this feature is not implemented yer.

**Comment by GitHorst** [comment]
ok, thank you! =)
