### ISSUE TITLE
F-Droid version outdated

### ISSUE THREAD

**Issue by gsantner** [naman14/Timber#259]
HI there, 
I just wanted to point out that the F-Droid version of Timber is outdated.

Build log:
<https://f-droid.org/wiki/page/naman14.timber>

**Comment by LoneFenris** [comment]
It appears that @naman14 may have accidentally re-added the the Fabric API entry to AndroidManifest.xml on the f-droid branch in https://github.com/naman14/Timber/commit/926127cc4f5e927e973b06e1782add6ba95e650b

I'm guessing this is what's preventing F-Droid from building v16

Tagging @krt16s as the original filer of #219

**Comment by offa** [comment]
Any news on this?

**Comment by i-kocevski** [comment]
This is a major issue and should be resolved ASAP!

**Comment by 464247853** [comment]
Anything we can do to solve this problem?

**Comment by gsantner** [comment]
@464247853  https://f-droid.org/packages/ch.blinkenlights.android.vanilla/ :D

**Comment by ikocevski** [comment]
@gsantner more like https://play.google.com/store/apps/details?id=com.foobar2000.foobar2000

**Comment by haverholm** [comment]
At this point the latest release is one year old anyway. Rushing to get that on F-droid rather than pushing a new version doesn't seem like a priority.

**Comment by gsantner** [comment]
I've stopped using / did use   Timber a long time ago and I'm happy with Vanilla. Closing.

**Comment by valerio-bozzolan** [comment]
@gsantner This bug is not solved even if our interest in the app may decrease. Please re-open this bug, some people may be still interested. :)

**Comment by z3ntu** [comment]
@naman14 Could you please make a flavor for the newest version as the current one on F-Droid is still 0.2b?

**Comment by gsantner** [comment]
Dont ask, owner seems not to be further interested in getting users via F-Droid.
