### ISSUE TITLE
Ads??

### ISSUE THREAD

**Issue by Technologx** [naman14/Timber#262]
Are we allowed to add ads to the app?

**Comment by avipars** [comment]
Check if the license allows it

**Comment by avipars** [comment]
(c) 2015 Naman Dwivedi

This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this app. If not, see https://www.gnu.org/licenses/.

So I think if you make any changes, you need to make it open source and share it. 

Menaing, no, you can't add ads to the app
