### ISSUE TITLE
Headphones don't work

### ISSUE THREAD

**Issue by joaomaridalho** [naman14/Timber#294]
The media controls on my headphones don't work

**Comment by rivaldi8** [comment]
It's already reported as #15. Maybe someone should change the description to reflect that it's not related to bluetooth.

**Comment by shailandraRajput** [comment]
Can you please close this issue it's now resolve
thanks

**Comment by joaomaridalho** [comment]
It's not resolved

**Comment by naman14** [comment]
Should be fixed now
