### ISSUE TITLE
Gradle's dependency cache may be corrupt

### ISSUE THREAD

**Issue by tracywang26** [naman14/Timber#298]
Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
I import this project to android studio 2.3.2 and can't build.
Anyone who knows the reason?

**Comment by naman14** [comment]
sync gradle with an active internet connection
