### ISSUE TITLE
Signed APK

### ISSUE THREAD

**Issue by Mardoqueu** [naman14/Timber#299]
The app is crashing when I create a signed apk

**Comment by Kasijjuf** [comment]
That's not enough information. Details please.

**Comment by Mardoqueu** [comment]
I already fixed. I was having problem with the api cash lyrics.

**Comment by Mardoqueu** [comment]
API that requires the API key that was generated with the application's SHA1. In this case, with the application now signed, it was necessary to re-run the API data generation process, but then use the SHA1 application dp signed application.
