### ISSUE TITLE
Music keeps playing after headphones are removed

### ISSUE THREAD

**Issue by kozross** [naman14/Timber#30]
Well, that or the auxiliary cable. This isn't an ideal behaviour - it'd be better if it stopped when this happened, kinda like Apollo does.

**Comment by naman14** [comment]
Thanks for mentioning. Working on it

**Comment by TheLastProject** [comment]
Must music players pause on disconnecting headphones, some make it a setting. Stopping is most likely not what you want, because you lose where you were in the song. I'm most likely nitpicking word choice here, though.

**Comment by kozross** [comment]
@TheLastProject Yeah, you are nitpicking, but it's a sensible nitpick. I meant 'pause'.

**Comment by naman14** [comment]
This also adds headset controls for play/pause, next and previous
