### ISSUE TITLE
Add some sort of empty view when no music files are on the phone

### ISSUE THREAD

**Issue by nikwen** [naman14/Timber#306]
Awesome music player!

Just one suggestion. This is how the app looks on a newly setup phone:

![Screenshot showing empty list view](https://user-images.githubusercontent.com/3309657/27977280-43d64f58-636a-11e7-941b-74190554b235.png)

I think that a better design could be applied here, i.e. some sort of empty state. See https://material.io/guidelines/patterns/empty-states.html.

**Comment by naman14** [comment]
Added now

**Comment by nikwen** [comment]
Awesome. Thanks! 🎉
