### ISSUE TITLE
Pause and playback dont work on the earphones

### ISSUE THREAD

**Issue by DennisWanjiru** [naman14/Timber#307]
When I pause the song from my earphones it takes long to pause but eventually does but on trying to playback the song via the earphones it doesn't work.

**Comment by rivaldi8** [comment]
This issue is already reported in #15. Would you mind adding your comment there? It would also be helpful to know your Timber and Android versions as well as your device model. Thanks!

**Comment by DennisWanjiru** [comment]
Am running android 5.1 and Timber 0.5b I bet that's the version of Timber.

**Comment by anburocky3** [comment]
Does anyone figure it out?  I cant pause with earphone button click too?

**Comment by shailandraRajput** [comment]
Check Out This commit [https://github.com/rivaldi8/Timber/commit/87679e13b6eec14d29b204e36d8082f9bb38ef2e](url)

**Comment by shailandraRajput** [comment]
Change code in app/src/main/java/com/naman14/timber/MusicService.java
delete This Line
mSession.setFlags(MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS);

add this line

mSession.setFlags(MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS                         | MediaSessionCompat.FLAG_HANDLES_MEDIA_BUTTONS);

**Comment by balogic** [comment]
I too have the same issue. Can't pause or resume from my Earphone.
Android version - 6.0.1
Timber version - 0.2b (F-Droid)

**Comment by anburocky3** [comment]
@naman14  developer dropped support?

**Comment by anburocky3** [comment]
Can anyone close this issue, it has been fixed with the pull request of @rivaldi8

**Comment by Kasijjuf** [comment]
@anburocky3 This shouldn't be closed until pull request #308 gets merged.

**Comment by DennisWanjiru** [comment]
Finally working.
