### ISSUE TITLE
Help. Google suspended my app

### ISSUE THREAD

**Issue by Flashems** [naman14/Timber#318]
They suspended my app due to spam report ???i m a newbie help me with this

**Comment by shameemreza** [comment]
Did you rename package and apps name, also did you change all the files like image, color etc etc? Google suspend apps only when they found same apps with same resources.

**Comment by Flashems** [comment]
I changed the package name ,app icon ,app name and made few changes but i
didn't changed the them.Thanks for your reply.

**Comment by shameemreza** [comment]
You have make a totally different design than the default, otherwise google wont publish your apps. By the way, I will suggest to support the original owner by contributing here instead publish new apps based on the source code. Thanks and welcome to the Android world.

**Comment by Flashems** [comment]
Thank you.I will do my best.
