### ISSUE TITLE
Tracks not sorted by their number

### ISSUE THREAD

**Issue by Siphonay** [naman14/Timber#32]
On every album I have, the tracks are not properly ordered. It looks random.

**Comment by naman14** [comment]
This has been resolved in 8a6717d02f4a39fae6665718d4a459f2ffbe43ff and is available in 0.12b release -https://github.com/naman14/Timber/blob/master/Changelog.md

**Comment by Siphonay** [comment]
Oh, okay. My bad, this version has not been pushed to F-Droid yet. Thanks for your work !
