### ISSUE TITLE
cannot find symbol variable play_billing_license_key

### ISSUE THREAD

**Issue by daliboss** [naman14/Timber#320]
![github1](https://user-images.githubusercontent.com/3904233/30311056-75798d22-978b-11e7-8752-cd3210cbefb7.PNG)

![github](https://user-images.githubusercontent.com/3904233/30310999-3cf584a6-978b-11e7-8588-99e59bcff1fd.PNG)
when i tried to generate  signed apk a got this error 

Error:(71, 59) error: cannot find symbol variable play_billing_license_key

in: \app\src\main\java\com\naman14\timber\activities\DonateActivity.java

ta line: bp = new BillingProcessor(this, getString(R.string.play_billing_license_key), this);

**Comment by shailandraRajput** [comment]
add this line in string.xml

<string name="play_billing_license_key">[Your play biling license key]</string>

it's work for me.(note if you only build apk you get a error for duplicate value. ignore it and click on generate signed apk )

**Comment by shailandraRajput** [comment]
add this line to string.xml

`<string name="play_billing_license_key">Your google license key</string>`

please note that it's get error when you try to build apk only. ignore it and click on generate signed apk

its work for me.

**Comment by daliboss** [comment]
here is my fix
bp = new BillingProcessor(this, "your license key", this);
