### ISSUE TITLE
Problems regarding foreign languages.

### ISSUE THREAD

**Issue by davidfrp** [naman14/Timber#324]
Some letters in foreign languages, such as æ, ø, and å, does not display correctly. This is a big concern for non-english speaking countries. Having the bug fix, or at least adding the option to "Force English" would be nice.

**Comment by rivaldi8** [comment]
Where are you seeing letters displayed incorrectly? In the UI or in music tags? If the problem is with music tags, I would check that the tags are properly encoded with UTF-8. My music with non-ASCII character is displayed just fine.

**Comment by davidfrp** [comment]
![image](https://user-images.githubusercontent.com/6499570/31046599-868629a8-a5fb-11e7-98d0-ddd7959b689d.png)

Hmm... everywhere. Not a single place in the app without this problem.

**Comment by davidfrp** [comment]
So far... only UI, Haven't checked for other occurrences.
![image](https://user-images.githubusercontent.com/6499570/31046611-ef816e0e-a5fb-11e7-8e76-d31f9acf8010.png)

**Comment by rivaldi8** [comment]
Ok, this is Danish, isn't it? The translation file (`app/src/main/res/values-da/strings.xml`) isn't properly encoded in UTF-8. Could you fix the problematic strings and send a pull request or attach the file?

**Comment by davidfrp** [comment]
I would. But the file looks complete. It is already formatted in UTF-8, and the strings looks fine.

**Comment by rivaldi8** [comment]
Where are you opening the file? From Android Studio it's the only language that looks wrong.
![strings](https://user-images.githubusercontent.com/1187977/31047208-998f407e-a606-11e7-9e83-64f70e069def.png)

**Comment by davidfrp** [comment]
I looked at the XML on GitHub... On GitHub the formatting and syntax of the strings and XML looks fine. 
I might be a programmer... but I don't have Android Studio installed.

**Comment by inzkhan** [comment]
![screenshot_1513740539](https://user-images.githubusercontent.com/33628287/34189971-0cfc9f32-e560-11e7-83b3-9aae9cf1d1d9.png)

Isn't it correct?
