### ISSUE TITLE
Visualizer is not stopping after changing music in playlists

### ISSUE THREAD

**Issue by mstburak** [naman14/Timber#339]
When click many musics to play in playlists, all musics visualizer is starting to play and not stopping until close to activity.
![untitled](https://user-images.githubusercontent.com/25405224/33175605-561c3342-d06d-11e7-9674-7f6ee6dfe78f.png)

**Comment by mstburak** [comment]
I solved this problem. Can you assign this issue to me please?

**Comment by naman14** [comment]
Fixed in 9c688c0fb62ccd1173b34fe9d4711cbc596d54c9
