### ISSUE TITLE
Notification tool doesn't change aspect of playlist

### ISSUE THREAD

**Issue by mstburak** [naman14/Timber#340]
When i open music in playlists, notification is open. And when i click next, previous or stop; it is doing action in background but nothing happen visually in playlist activity. For example;
At start, I chose 1 music.
![untitled2](https://user-images.githubusercontent.com/25405224/33218455-054531d0-d14e-11e7-8d36-e83fd2652e3e.png)

As you see, in notification tool we started to see now playing music.
![untitled](https://user-images.githubusercontent.com/25405224/33218489-31408a5a-d14e-11e7-8683-ab0792085dbc.png)

Then, I clicked next button to open next music, and Timber started to play next music.
![untitled3](https://user-images.githubusercontent.com/25405224/33218549-88514000-d14e-11e7-81cd-8cf6084a6c8c.png)

But in playlistactivity nothing happened.
![untitled4](https://user-images.githubusercontent.com/25405224/33218575-ac8a095c-d14e-11e7-8284-91e07fce415f.png)

**Comment by mstburak** [comment]
Can you assign this issue to me please?

**Comment by naman14** [comment]
Fixed in 9c688c0fb62ccd1173b34fe9d4711cbc596d54c9
