### ISSUE TITLE
Error test on emulator

### ISSUE THREAD

**Issue by joseliko7** [naman14/Timber#35]
Error:Execution failed for task ':app:compileDebugAidl'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Jose\AppData\Local\Android\sdk\build-tools\23.0.1\aidl.exe'' finished with non-zero exit value 1

How to fix it?

**Comment by solnj** [comment]
Do you have installed the Android SDK build-tools?

**Comment by rpairo** [comment]
Use Android Studio on Linux or OS X

**Comment by naman14** [comment]
Install 23.0.1 build tools and check the above mentioned links
