### ISSUE TITLE
Online Music Player

### ISSUE THREAD

**Issue by azimjohn** [naman14/Timber#403]
Great music player!

I created a restful api (artists, albums, songs), wanted to intergrate with the music player.
I am a novice android developer, need help to turn the local player to online one.

What files and which part of the code should I be looking at to do it?
Thank you

**Comment by anburocky3** [comment]
You can create a separate menu mentioning as "Online MP3" and use the awesome library "Retrofit" and integrate accordingly. You need some intermediate skill to do it. Good Luck.
