### ISSUE TITLE
Artist Fragment Broken on API29

### ISSUE THREAD

**Issue by TheTerminatorOfProgramming** [naman14/Timber#448]
After Updating the API to API29 the ArtistFragment Crashes on load.
I have narrowed down the issue to the following line in ArtistMusicFragment.
 mSongAdapter = new ArtistSongAdapter(getActivity(), songList, artistID);

Please tell me how to fix this issue? 

thanks

**Comment by creativetrendsapps** [comment]
> After Updating the API to API29 the ArtistFragment Crashes on load.
> I have narrowed down the issue to the following line in ArtistMusicFragment.
> mSongAdapter = new ArtistSongAdapter(getActivity(), songList, artistID);
> 
> Please tell me how to fix this issue?
> 
> thanks

Wouldn't the logcat tell you the line that is causing the crash? Is the Activity null? songList null? artistId null?
