### ISSUE TITLE
Import Music From Google Play

### ISSUE THREAD

**Issue by iamjawa** [naman14/Timber#46]
At the moment the music on the app is only importing from that I manually transferred to my device rather than the music I downloaded from my Google Play Music Account. Please Fix This! This app is awesome and if this issue is fixed I will use this entirely instead of Google Play Music.

**Comment by iKermitKiller** [comment]
Music pinned to your device through Play Music cannot be read by other players without root access.

**Comment by TheJawaEyes** [comment]
I have Root Access but had Timber didn't request root access, so I had no option to import the music from Play Music.

**Comment by crutchcorn** [comment]
Another use case of #8
