### ISSUE TITLE
Titles played in wrong order for Multi-CD albums

### ISSUE THREAD

**Issue by reieRMeister** [naman14/Timber#56]
Songs of a Multi-CD album are not played in the order they are displayed in.

**Comment by Tangleworm** [comment]
Hey naman14, is it alright if my peers and I work on this bug and #55? :)

**Comment by naman14** [comment]
@Tangleworm Of course, that would be great!

**Comment by Tangleworm** [comment]
@naman14 Awesome, thanks!

**Comment by reieRMeister** [comment]
Looks fixed to me. Thank you, good work!
