### ISSUE TITLE
Timber doesn't appear in Pebble's App

### ISSUE THREAD

**Issue by xtotdam** [naman14/Timber#70]
Timber doesn't appear in official Pebble app as a music player that can be controlled directly from watch. It is weird, because Timber actually sends correct information of a playing at the moment song to the official Music watchapp to the watch. Pressing the buttons trying to pause/play the next song/etc leads to launching the chosen music player (as it can be predicted)

<img src="https://cloud.githubusercontent.com/assets/5108025/10648989/303d3b30-784a-11e5-85d1-f882242db096.png" width="300">
<img src="https://cloud.githubusercontent.com/assets/5108025/10649094/d1f31968-784a-11e5-8bad-b0b568785baa.JPG" width="600">

**Comment by jan509** [comment]
I don't know anything about Watches or something similar, so don't hate me if I am wrong but I think that Timber needs to integrate the Pebble Watch. iOS Apps for example need also a specific version to be used with an Apple watch.

**Comment by xtotdam** [comment]
I'm not very sure about integration, as long as gReader is RSS reader and Chrome is Chrome (Pebble support from Google browser :) ). But I'm going to investigate how to add Pebble support (even occasionally) and will provide you results asap.

**Comment by xtotdam** [comment]
Hi! I am sorry for my absense. I don't really know, what exactly changed (is it new ROM I've installed or did the app update in the right place) but Timber finally appeared in Pebble app and can now be chosen as a default Music player. Great job! Thank you!
