### ISSUE TITLE
[Feature request] Automatically pause music when earphones/headphones are unplugged

### ISSUE THREAD

**Issue by okungnyo** [naman14/Timber#76]

**Comment by naman14** [comment]
Check #39, have already been added

**Comment by okungnyo** [comment]
Huh? I just tested it out, it's not working for me.

**Comment by naman14** [comment]
Play store version or built from source? Changes haven't been updated on play store yet

**Comment by okungnyo** [comment]
Oh, Play Store!

Sorry for being dumb..
