### ISSUE TITLE
Folder browsing 

### ISSUE THREAD

**Issue by crutchcorn** [naman14/Timber#8]
Allow me to browse folders and play from there as a group of songs. Playlists don't export so great for me so I make folders to listen to

**Comment by naman14** [comment]
Folder browsing is currently in progress

**Comment by crutchcorn** [comment]
Thanks so much!

**Comment by itsmortoncornelius** [comment]
Nice

**Comment by licaon-kter** [comment]
nice

**Comment by hawkeyed** [comment]
I am waiting for this. The app looks pretty cool.

**Comment by naman14** [comment]
Have been added in latest release
