### ISSUE TITLE
Straight away app crashes on start

### ISSUE THREAD

**Issue by AllamBalraj** [naman14/Timber#82]
i am getting this ERROR,
java.lang.RuntimeException: Unable to start activity ComponentInfo{naman14.timber.debug/com.naman14.timber.activities.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.design.widget.NavigationView

**Comment by naman14** [comment]
Should have been fixed now. Try again after pulling latest commits.
Or is the crash in the play store version?

**Comment by AllamBalraj** [comment]
Yeah!!! It works now .. Thank You. And play store version works fine.
