### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Airon90** [naman14/Timber#86]
Hi, I'd like to translate your app into Italian and Esperanto but I don't know how to do that. 
Could someone explain it in a "How to contribute" section of [README.md](https://github.com/naman14/Timber/blob/master/README.md)? Thank you very much!

**Comment by licaon-kter** [comment]
Go to https://github.com/naman14/Timber/blob/master/app/src/main/res/values-it/strings.xml
click on the pencil on the right of History button -> edit -> write something in `Propose file change` -> press green "Propose file change" -> press green Pull request -> done ;)

If the language has no `/app/src/main/res/values/` folder you need to fork, create etc, or ask the dev to make a `/app/src/main/res/values-eo/strings.xml` (for Esperanto) and then edit it here.

**Comment by Airon90** [comment]
Ok, I just need to know where the files are located :P 
Is the file updated to the latest version or do I have to add by hand missing keys (i.e. app_name is missing)?
Thank you very much

**Comment by licaon-kter** [comment]
I guess it should be updated, do open the one: https://github.com/naman14/Timber/blob/master/app/src/main/res/values/strings.xml in a side window and make sure.

**Comment by Airon90** [comment]
Done: #87
