### ISSUE TITLE
[Bug] [UX] App "crashes" when exiting now playing

### ISSUE THREAD

**Issue by smichel17** [naman14/Timber#96]
100% repro on rooted verizon galaxy S4, SCH-I545, lollipop 5.0.1
 Steps to reproduce:

1. Open Timber, play any song.
2. Hit home button
3. Open Timber from the notification drawer.
4. Hit either the back button in the upper left, or the 'back' system/hardware key.

Expected result: App returns to library
Actual result: Return home with "Unfortunately, Timber has stopped." message. However, Timber continues to play music.

If you can't reproduce this bug, let me know what logs you need and I'll be happy to provide them.

**Comment by naman14** [comment]
Can't reproduce, working fine on my nexus 6.
Please provide crash log

**Comment by naman14** [comment]
Will be working as expected in next release
