### ISSUE TITLE
Palette color binding incorrect

### ISSUE THREAD

**Issue by se-bastiaan** [naman14/Timber#97]
In the albumlist the color of the art is used as background color of the title view. The color of this view is not being reset when the recyclerview is bound again.

**Comment by naman14** [comment]
steps to reproduce? Works fine for me

**Comment by se-bastiaan** [comment]
There are no real steps, since it's really random. Just make sure you have one album without image and then start scrolling. Since there is no image the palette code will not be executed and the color of the previous item (that had an image) will still be used.

https://github.com/naman14/Timber/blob/962912681e51b86205f83007e7e7002ae158ce4c/app/src/main/java/com/naman14/timber/adapters/AlbumAdapter.java#L80

**Comment by naman14** [comment]
Oh, understood now. Thanks for the explanation:) 
Fixing now
