### ISSUE TITLE
Unable to select the equilizer option etc

### ISSUE THREAD

**Issue by rishabmehta** [naman14/Timber#99]
* there are few bugs like - the song title is different from the song which is being played ... (This happens sometimes)
*I am not able to open equilizer settings... Whenever I select the option ...nothing happens....
* auto playlists works slowly!

I had also sent an email about this and with few more suggestions....
Please do acknowledge my email as well as this issue 
22mehta22@gmail.com

**Comment by zeustl** [comment]
Regarding the equalizer issue you mentioned. If I'm not mistaken the app uses the system equalizer and on some different vendor implementations ( such as HTC roms ) you don't have a system eq. available . 

On samsung for example ,I can access the equalizer without any problems , but on an HTC one I can't

**Comment by naman14** [comment]
Equalizer should be accesible in release 0.13b on Google Play (If your device has an audio effects intent)
